### PR TITLE
Updated versions (cabal + stack) & adding tileType

### PR DESCRIPTION
**Pull request by andrevdm**
- Cabal to 2.2
 - Stack to lts-12.9
 - Bounds to latest working with lts-12.9

### CODE REVIEW

**Comment by andrevdm** [comment]
Builds with stack `lts-12.9` and `cabal new-build`.
Tests pass

**Comment by andrevdm** [comment]
I've added the `tileType` property as this is a top level property that Tile 1.1.6 (possibly) earlier supports. I've followed your unit test style as far as I can see. All tests passing

**Comment by schell** [comment]
Merged! 

Just a heads up - this repo isn't being actively maintained. I've moved to https://github.com/schell/aeson-tiled. Feel free to upload to stackage at your discretion.

**Comment by andrevdm** [comment]
Oh right, thanks :)

Perhaps a README to point to the new project would be a good idea? I'll PR one later for you if you like. The aeson code is certainly easier to work with than the xml!

**Pull request merged**
